import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { JitsiMeeting } from '@jitsi/react-sdk';

export default function MeetingRoom() {
  const { roomId } = useParams();
  const navigate = useNavigate();

  // If no roomId is provided in the URL, create a random one
  // In a real app, this roomId would be generated by your backend when a session is booked!
  const actualRoomId = roomId || 'studybudget-demo-room-' + Math.random().toString(36).substring(7);

  return (
    <div style={{ height: 'calc(100vh - 70px)', width: '100%', backgroundColor: '#111' }}>
      <JitsiMeeting
        domain="meet.jit.si"
        roomName={actualRoomId}
        configOverwrite={{
          startWithAudioMuted: true,
          startWithVideoMuted: true,
          disableModeratorIndicator: true,
          resolution: 720,
        }}
        interfaceConfigOverwrite={{
          DISABLE_JOIN_LEAVE_NOTIFICATIONS: true,
        }}
        userInfo={{
          displayName: 'StudyBudget Student/Tutor',
        }}
        onApiReady={(externalApi) => {
          // When the user clicks the red "hang up" button, redirect them back to the dashboard
          externalApi.addListener('videoConferenceLeft', () => {
             navigate('/dashboard');
          });
        }}
        getIFrameRef={(iframeRef) => {
          iframeRef.style.height = '100%';
          iframeRef.style.width = '100%';
          // Small style fix to hide iframe borders
          iframeRef.style.border = 'none';
        }}
        spinner={() => (
           <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
             Loading Video Room...
           </div>
        )}
      />
    </div>
  );
}
